version: "3.7"
services:
    app:
        container_name: weather_app
        build: ./
        ports:
            - 5001:5000
        volumes:
            - ./datapoints:/home/data
volumes: 
  datapoints:
