version: "3"
services:
    app:
        container_name: weather_sense
        build: .
        privileged: true
        ports:
            - 5001:5000
        volumes:
            - ./datapoints:/home/data
volumes: 
  datapoints:
